Fix SIMVA Front
e-ucm/simva-front pull request #14
Opened 2024-05-20 12:38 UTC by jujusb

2024-06-04 12:43 UTC, imartinezortiz requested changes

2024-06-04 12:43 UTC, imartinezortiz commented on config.js
> +config.simva.host = process.env.SIMVA_HOST || 'external.test'
I think the previous default value is ok

2024-06-04 12:43 UTC, imartinezortiz commented on public/activities/miniopainter.js
Not specific to this change, but related to new code that requires to generate a string. Note that current browsers supports the backticks string definition that is far easier to use in a similar problem like this one.

2024-06-04 12:43 UTC, imartinezortiz commented on routes/routes/users.js
Would be nice to migrate in the future to a Backend For Fronted approach, so the JS of the frontend do not require to deal with JWT, just using "credentials" (e.g. cookies) once the user has logged in. This is the common approach to SPA nowadays

2024-06-07 10:19 UTC, jujusb commented on routes/routes/users.js
issue opened

2024-06-11 07:55 UTC, jujusb commented on public/activities/miniopainter.js
fixed in all scripts

2024-06-19 13:59 UTC, merged